### PR TITLE
add 'tree' prefix to id placeholder

### PR DESCRIPTION
**Pull request by jar398**
Not tested yet... don't see what can go wrong, but if someone insists I'll try it out before going to production

### CODE REVIEW

**Comment by kcranston** [comment]
Where is this being added in the UI?

**Comment by kcranston** [comment]
Ah, in the Add new tree to collection. Is the prefix always 'tree'?

**Comment by jar398** [comment]
It's only the placeholder, so has no effect on what the webapp does. But it can affect what the user does, by encouraging them to put the full id there, such as tree1234 or Tr1234, instead of just the number 1234, which would be wrong.  We could put any prefix we like there, but we ought to put some prefix to avoid misleading people into thinking that an integer could ever be an id. This situation occurs elsewhere in the webapp and there it properly has a prefix.

**Comment by kcranston** [comment]
Addresses issue #873

**Pull request merged**
