### PR TITLE
Implement a toggle to show all study details.

### PR DESCRIPTION
**Pull request by jimallman**
This is done as a stateful view ("compact" or "full"), so it can be shared in a URL and easily reloaded automatically. Addresses #986.

This is working now on **devtree**. See the issue above for more details.

### CODE REVIEW

**Comment by kcranston** [comment]
Two requests:
1. Can we remove this line from the full display: `This study has not been tagged. `
2. Can we put the publication link immediately after the publication reference (without a link break) and simply not show if not present?

**Comment by kcranston** [comment]
Also, when you flip the toggle from compact to full, it puts you back to the first page of results

**Comment by jimallman** [comment]
> Also, when you flip the toggle from compact to full, it puts you back to the first page of results

This is now fixed on **devtree**. As a side effect, pagination movements are now tracked in the URL (and added to browser history, which might be annoying for some). This is only true for the study list; other filtered lists in the curation app are unchanged.

Hm, should we reset to page 1 when changing the sort order (e.g. oldest first to newest first)?

**Comment by jimallman** [comment]
> Can we remove this line from the full display: This study has not been tagged.
> Can we put the publication link immediately after the publication reference (without a link break) and simply not show if not present?

These changes are available for review on **devtree**.

**Pull request merged**
