### PR TITLE
Change presentation of tree status vs. current and next synthesis

### PR DESCRIPTION
**Pull request by jimallman**
Details in comments below. Addresses #1042 by implementing the [accepted solution shown here](https://github.com/OpenTreeOfLife/opentree/issues/1042#issuecomment-248663245).

N.B. This correctly captures trees marked as "preferred" in the old Nexson, but does not detect the prior inclusion of a tree in a synthesis collection! This will require a batch operation or more client-side
smarts.

This is working now on **devtree**.

### CODE REVIEW

**Comment by jimallman** [comment]
In accordance with [this issue describing Nexson changes](https://github.com/OpenTreeOfLife/phylesystem-api/issues/191), the property name is now `ot:candidateForSynthesis` and we use the enumerated values described there. These are [mapped to friendly descriptions](https://github.com/OpenTreeOfLife/opentree/pull/1068/commits/77a1193b25e5e6261cb9aa9b0e8593fd7be7ba33#diff-ec50a802bd4aa427fc715b6e1989c6a2R2741) for display in the curation app.

Also addresses https://github.com/OpenTreeOfLife/phylesystem-1/issues/12

**Comment by jar398** [comment]
Backward compatible with old nexsons?​

**Comment by jimallman** [comment]
> Backward compatible with old nexsons?​

I believe so. There should be no trees on production with a `ot:readyForSynthesis` or `ot:candidateForSynthesis` property, and the editor [adds the missing property with a sensible value](https://github.com/OpenTreeOfLife/opentree/pull/1068/files#diff-ec50a802bd4aa427fc715b6e1989c6a2R827).

**Comment by kcranston** [comment]
Changes here might be moot, depending on outcome of #1070

**Comment by jimallman** [comment]
Needs a quick for for view (vs. edit) property, which shows a "raw" value instead of friendly string.

**Comment by jimallman** [comment]
OK, we now show friendly strings in the read-only Trees tab, for example https://devtree.opentreeoflife.org/curator/study/view/pg_2606?tab=trees

**Comment by jimallman** [comment]
This PR is **on hold**, pending the review and implementation of [the changes described here](https://github.com/OpenTreeOfLife/phylesystem-api/issues/191#issuecomment-254919291).

**Comment by kcranston** [comment]
Now that we have consensus on nexson syntax in https://github.com/OpenTreeOfLife/opentree/issues/1070 and the new phylesystem service with https://github.com/OpenTreeOfLife/phylesystem-api/pull/210 is there anything preventing this from being wrapped up?

**Comment by kcranston** [comment]
Looking through the PR review notes, I see a [comment about this waiting for otindex](https://gitter.im/OpenTreeOfLife/public?at=5824c3dedf5ae966453e9877). I don't know what dependency on otindex you mean, @jimallman . Can you clarify?

**Comment by jimallman** [comment]
My mistake! I was thinking of the service that lists all the trees in synth-input collections. I forgot that this is already available as `/phylesystem/v1/trees_in_synth`. I have more work to do on this feature, but the latest version is happening in [another branch that should probably replace this one](https://github.com/OpenTreeOfLife/opentree/tree/improved-tree-synth-status) in the PR list.

**Comment by jimallman** [comment]
Closing this in favor of the [revised feature branch](https://github.com/OpenTreeOfLife/opentree/tree/improved-tree-synth-status)...

**Pull request closed without merging**
