### PR TITLE
Update about

### PR DESCRIPTION
**Pull request by snacktavish**
Upgrade myself from postdoc :P , acknowledge current NSF grant.

### CODE REVIEW

**Comment by snacktavish** [comment]
Currently deployed on devtree.

**Comment by jimallman** [comment]
> Currently deployed on devtree.

Looks good to me! Good catch on [the Credits page](https://devtree.opentreeoflife.org/opentree/about/credits) -- I assume that's old and unused for some time, but I suppose it's possible there are old inbound links.

(Just a quick reminder, as we have a history of parallel feature development in this repo. Our usual procedure is to merge these changes to the `development` branch, and always deploy that one. I've done so, so this is now visible on **devtree** along with some other recent changes.)

**Comment by snacktavish** [comment]
Ah I forgot that was approach. Should I close this a make PR development to master instead?

**Comment by jimallman** [comment]
No worries, this PR is just right (`feature-branch` ==> `master`). Merging development to master would introduce all kinds of unwanted junk (abandoned features, unfinished stuff, clumsy merge results). Ask me how I know... :bowtie:

**Pull request merged**
