### PR TITLE
OTU mapping fixes

### PR DESCRIPTION
**Pull request by jimallman**
Latest fixes for @snacktavish 's bug reports on taxonomic amendments, see https://github.com/OpenTreeOfLife/opentree/issues/1260

### CODE REVIEW

**Comment by mtholder** [comment]
Hi @jimallman , Has this been tested with the 2 recently merged PRs? I was thinking about merging this and then deploying all 3 if that sounds reasonable to you.

**Comment by jimallman** [comment]
I haven't tested amendments since the more recent changes, but they're completely unrelated so should be quite compatible. I'll give it a quick test on **devtree** now and report back.

**Comment by jimallman** [comment]
@mtholder This seems to be working fine on the latest **devtree**. I did hit an unrelated error on phylesystem-api, a missing `_LOG` definition that was recently found and [fixed directly on the master branch](https://github.com/OpenTreeOfLife/phylesystem-api/commit/569efaed343fd3e783d57818ccba2461bf990c5a) of phylesystem-api. Please re-deploy that as well.

**Comment by mtholder** [comment]
Yeah. I checked. That change to phyleystem-api is indeed on phylesystemapi.opentreeoflife.org already.
I'll merge this and try the redeploy

**Pull request merged**
