### PR TITLE
Collections in curator profile

### PR DESCRIPTION
**Pull request by jimallman**
This addresses a number of related bugs re: collections and the curator profile page:

- Adding or editing a tree collection is now recognized as OpenTree activity, so a user who has only done these things will have a proper curator profile page.

- The "their tree collections" list will appear for any valid OpenTree user.

- Fixed a server-side bug (500 error) when we show the "no such user in GitHub" page.

- We show tree-collection stats for an active curator, in a compact format.

- We show an explanation for missing study stats, pending [OTI fixes described elsewhere](https://github.com/OpenTreeOfLife/oti/issues/35).

- We restore the 'Tree collections' menu (in the app's main menubar) and enable 'Add new collection' from any page in the curation app.

### CODE REVIEW

**Comment by jimallman** [comment]
This fixes #902.

**Comment by jimallman** [comment]
This also fixes #874.

**Comment by kcranston** [comment]
Assuming that collections still suffer from the larger problem of not being able to associate activity with users that don't have a public email address on their GitHub profile?

**Comment by jimallman** [comment]
Good question @kcranston! This activity is tracked through peyotl, so it likely behaves like study curation.

**Comment by jimallman** [comment]
Two requested changes:
 - Remove "(details below)" if there are no collections to show
 - Remove link to pending oti issue, just a more general message here
   > Reliable counts are coming soon.

**Pull request merged**
